### ISSUE TITLE
adc_gen cell cannot find problem

### ISSUE THREAD

**Issue by fan-deng2000** [idea-fasoc/fasoc#10]
When I run adc_gen tsmc65lp macro mode, and this is some error, and I have checked the folder, I have also attached the result in the picture

![adc_gen_problem](https://user-images.githubusercontent.com/61760372/102444749-e8321380-3ff7-11eb-87e9-94ebd24a45d5.png)

**Comment by fan-deng2000** [comment]
I have meet first picture's error, and I have found the sar.json file in the temp folder, so I just tried rename the temp folder to output.
And the error in second picture appears after running
I have just tried with the adc_data.jason and macro mode with tsmc65lp

![image](https://user-images.githubusercontent.com/61760372/102702566-3c283c80-4232-11eb-8068-377bb60cf2aa.png)

![image](https://user-images.githubusercontent.com/61760372/102702556-2450b880-4232-11eb-9d00-411be7292822.png)

**Comment by msaligane** [comment]
Fixed by [6ce3bb8](https://github.com/idea-fasoc/fasoc_private/compare/64180139352a...8a7de10b16e4)
