### ISSUE TITLE
cdc_gen hspice not found

### ISSUE THREAD

**Issue by fan-deng2000** [idea-fasoc/fasoc#12]
I have checked the private folder, and there is no hspice there, is that some linkage problem

![image](https://user-images.githubusercontent.com/61760372/102447913-f7688f80-3ffe-11eb-9d61-3c892fc62700.png)

**Comment by fan-deng2000** [comment]
tools/cdc-gen.py --specfile test.json --output output --platform tsmc65lp --mode macro

This is the command

**Comment by fan-deng2000** [comment]
Same problem after have the tsmc library access

**Comment by msaligane** [comment]
@wenbodd Could you please address this issue.

**Comment by msaligane** [comment]
fixed in [`8a102cf`](**https://github.com/idea-fasoc/fasoc/commit/8a102cf02e14809e7d725b750d79608998d046d6**)
