### ISSUE TITLE
temp_sensor_gen incorrect file name

### ISSUE THREAD

**Issue by fan-deng2000** [idea-fasoc/fasoc#14]
Hi, please take a look at the src folder, I think it is just a mismatch between the python and the folder files

![image](https://user-images.githubusercontent.com/61760372/102449706-ddc94700-4002-11eb-965f-48d872e6f0f9.png)

**Comment by fan-deng2000** [comment]
tools/temp-sense-gen.py --specfile  test.json --output output --platform tsmc65lp --mode macro

This is the command that I have tried

**Comment by fan-deng2000** [comment]
still have this error after having the tsmc library

**Comment by msaligane** [comment]
Fixed by [60c1e7b](url)
There is a VIN that still shows up at the top which is an artifact from the previous tempsense version. We are updating the aux cells to fix that.
