### ISSUE TITLE
dcdc_gen

### ISSUE THREAD

**Issue by fan-deng2000** [idea-fasoc/fasoc#15]
Is it some issue in the folder create part, as it will not create the simulation folder by itself 

![image](https://user-images.githubusercontent.com/61760372/102535090-b790bf00-4075-11eb-9bdb-acd46c2f2bc3.png)

**Comment by fan-deng2000** [comment]
tools/dcdc-gen.py --specfile test.json --output output --platform tsmc65lp --mode macro

Command I have tried that result in this error

**Comment by msaligane** [comment]
@bbulsa Can you take a look at this?

**Comment by fan-deng2000** [comment]
still the same problem after having the tsmc library

**Comment by bbulsa** [comment]
Hi,

It seems a few empty directories were automatically removed by Github when I uploaded the scripts. Try the following first (manual directory generation), and let me know if it works.
 
cd fasoc/private/generators/dcdc-gen
mkdir simulation
mkdir extraction
