### ISSUE TITLE
submodule update error after having access to all repos

### ISSUE THREAD

**Issue by fan-deng2000** [idea-fasoc/fasoc#17]
I have pull a new folder and runs the following command, also, I have access to all repos. And I am get this error, please take a look

![image](https://user-images.githubusercontent.com/61760372/102727286-cfc14200-42f2-11eb-89ab-780cc9d0a151.png)

**Comment by fan-deng2000** [comment]
The issue is m0sdk submodule

**Comment by ycherivirala** [comment]
Released the changes in [6081a6f](https://github.com/idea-fasoc/fasoc/commit/6081a6f3cf127ca409a073ce3c1f6dcabc0198f0)
