### ISSUE TITLE
LDO_gen full mode issue

### ISSUE THREAD

**Issue by chenliyumich** [idea-fasoc/fasoc#18]
I was using calibre/2019.3_25 when "make gen_12lp_full" but it didn't generate ldo.pex.netlist which cause the post pex simulation not working. I changed to calibre/2020.3_38.22_aoj and solved the issue.

**Comment by ycherivirala** [comment]
Added a comment in the README file to let the user know which calibre version to use for Full mode in 12LP technology. Released the changes in [df7a1c0](https://github.com/idea-fasoc/fasoc/commit/df7a1c0a0c13d9d1c23c45da1bb6ffc3033c874b)
