### ISSUE TITLE
Is it possible to replace closed source tools with open source equivalents?

### ISSUE THREAD

**Issue by mithro** [idea-fasoc/fasoc#2]
There is lot of information about potentially alternative flows in a doc at http://j.mp/openeda-diagram

[The OpenRoad Project](https://theopenroadproject.org) seems like it would also be a potentially good option.

**Comment by msaligane** [comment]
Hi Tim,

Yes this is something that is on our list of things to do. We did some trials during the IE where we were able to synthesize/apr the temp. sensor but with way too many interventions.
We agreed internally that the first step to do so is to do the public release which consists of generators flow scrubbed from anything that is confidential (PDK, tools etc..). Now that this step is done we will be trying opensource tools such as OpenRoad and see how it goes. 

Thanks for sharing the links, we will look at them carefully.
