### ISSUE TITLE
Documentation on current set of generators

### ISSUE THREAD

**Issue by mithro** [idea-fasoc/fasoc#4]
You seem to have a whole bunch of generators at https://github.com/idea-fasoc/fasoc/tree/master/generators but very little documentation on what the generators do, how types of ranges they work on, how they are used, etc.

Might be a good idea to add a top level README.md to the generators directory and then a bit more information to each of the generators README files.

**Comment by wentzloff** [comment]
README files have been updated with more details. Closing issue.
