### ISSUE TITLE
Remove "This is the readme" from top of README files

### ISSUE THREAD

**Issue by mithro** [idea-fasoc/fasoc#6]
A lot of the README files seem to have a "This is the readme" at the top of them. IE https://github.com/idea-fasoc/fasoc/tree/master/generators/adc-gen

The title should be the second line.

**Comment by ycherivirala** [comment]
Changes released in [fc79ca9](https://github.com/idea-fasoc/fasoc/commit/fc79ca9bab995818a53d9ee51824ccd3f65852fe#diff-3738ada32084039ec39ae0d648443532007dd47d8bfaaf909428d36ab39452f2)
