### ISSUE TITLE
check_env.py small bugs

### ISSUE THREAD

**Issue by fan-deng2000** [idea-fasoc/fasoc#8]
There are some small bugs on the check_env, I am getting errors for checking python version and other cadence tools. And there should be some check for the python libraries like numpy and so on. So just have that updated.

**Comment by tajayi** [comment]
Thanks. Please try out the new changes in 3eb5ee2ba24041cdca2281853a3718346a3464f1

**Comment by ycherivirala** [comment]
Hi Fan, do you still have his issue ?
